language: node_js
sudo: false
node_js:
  - "5"
  - "4"
  - "0.12"
install:
  - npm install -g codecov
  - npm install
script:
  - npm run -s jshint
  - travis_retry npm test
after_success:
  - npm run codecov
